# Generated by Django 4.2.5 on 2023-09-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=12)),
                ("salary", models.FloatField()),
                ("city", models.CharField(max_length=50)),
                ("state", models.TextField()),
            ],
        ),
    ]
